version: "2.27.0"
services:
  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    ports:
      - $LOCAL_DB_PORT:$DB_PORT
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./
    image: logeshlogi/attendance-backend:latest
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - DB_NAME=$DB_NAME
      - DOCKER_DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - PORT=$PORT
      - SECRET_KEY=$SECRET_KEY
      - JWT_EXPIRATION=$JWT_EXPIRATION
      - DIALECT=$DIALECT
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres-db
volumes:
  db-data:
